// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DJkmefTUUjimbP1KVs5l6sEB2ismhPs',
    appId: '1:753766158869:web:a6ca5375ef2f815ec3341c',
    messagingSenderId: '753766158869',
    projectId: 'lista-compras-9bb4c',
    authDomain: 'lista-compras-9bb4c.firebaseapp.com',
    storageBucket: 'lista-compras-9bb4c.firebasestorage.app',
    measurementId: 'G-SM53M7X3LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kMltMXrW-xA_7_el0gJ8097Q8F_Uwgk',
    appId: '1:753766158869:android:3145e1b3dc715d88c3341c',
    messagingSenderId: '753766158869',
    projectId: 'lista-compras-9bb4c',
    storageBucket: 'lista-compras-9bb4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHD3fnep6JiKHPzpvLQ7k2AyhGoce7AvQ',
    appId: '1:753766158869:ios:b2e78a6d7f853235c3341c',
    messagingSenderId: '753766158869',
    projectId: 'lista-compras-9bb4c',
    storageBucket: 'lista-compras-9bb4c.firebasestorage.app',
    iosBundleId: 'com.example.listaCompras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHD3fnep6JiKHPzpvLQ7k2AyhGoce7AvQ',
    appId: '1:753766158869:ios:b2e78a6d7f853235c3341c',
    messagingSenderId: '753766158869',
    projectId: 'lista-compras-9bb4c',
    storageBucket: 'lista-compras-9bb4c.firebasestorage.app',
    iosBundleId: 'com.example.listaCompras',
  );
}
